# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    inogre:
      - dependency-name: google-cloud-bigquery
        versions:
          - 1.30.0
      - dependency-name: carrierwave
        versions:
          - 2.2.0
      - dependency-name: bootstrap
        versions:
          - "> 4.3.1"
          - "< 5"
    target-branch: master
    rebase-strategy: auto
